### ISSUE TITLE
Other Languages (Additional Work 1)

### ISSUE THREAD

**Issue by SerenaWhite** [DataVis3/datavis#10]
17-1: Other Languages pg 375

**Comment by Kraft-Bandicoot** [comment]
ill do this one!

**Comment by Kraft-Bandicoot** [comment]
so I uploaded the html files for all the different languages but Im not sure if they are working.

**Comment by SerenaWhite** [comment]
I'll check it now!

**Comment by SerenaWhite** [comment]
Just checked seems like it all works 👍 

Solved by pull request #24
