### ISSUE TITLE
Active Discussions (Additional Work 2)

### ISSUE THREAD

**Issue by SerenaWhite** [DataVis3/datavis#11]
17-2: Active Discussions pg 375

**Comment by luispaez24** [comment]
I finished 17-2 but how do I post it

**Comment by SerenaWhite** [comment]
Just saw this now, I can walk you through using git tomorrow but there are tutorials on how to use it in [the contributor's guide][cg], it's completely filled out through, like its missing sections on how to install git.

[cg]: https://github.com/DataVis3/datavis/blob/master/CONTRIBUTOR.md

**Comment by luispaez24** [comment]
Ok I'll try that
