### ISSUE TITLE
Scatter Plots with Plotly (Section 1)

### ISSUE THREAD

**Issue by SerenaWhite** [DataVis3/datavis#4]
pg 306 (Ch 15 Start) to pg 315 (Saving Your Plots automatically)

Submit a Pull Request from a branch with just this section's work and we can link it to this issue.

**Comment by Kraft-Bandicoot** [comment]
`# Alexander Rankin

import matplotlib.pyplot as plt

x_values = range(1, 1001)
y_values = [x**2 for x in x_values]

plt.style.use('seaborn')
fig, ax = plt.subplots()
ax.scatter(x_values, y_values, c=y_values, cmap=plt.cm.Blues, s=10)

# Set chart title and label axis
ax.set_title("Square Numbers", fontsize=24)
ax.set_xlabel("Value", fontsize=14)
ax.set_ylabel("Square of Values", fontsize=14)

# Set size of tick labels
ax.axis([0, 1100, 0, 1100000])

plt.show()

# replace above line with below line to save file
# plt.savefig('squares_plot.png', bbox_inches='tight')
`

**Comment by Kraft-Bandicoot** [comment]
lol im not sure how to use this but this is the first section

**Comment by SerenaWhite** [comment]
Just double-checked your code, and it's correct for the scatter_sqaures file. To upload it an easier way is by using git to upload files directly there is a guide on that [here][contributor]

[contributor]: https://github.com/DataVis3/datavis/blob/master/CONTRIBUTOR.md

**Comment by SerenaWhite** [comment]
The scatter_squares file is correct but you're missing the mpl_squares file.
