### ISSUE TITLE
Random Walks in Plotly (Section 2)

### ISSUE THREAD

**Issue by SerenaWhite** [DataVis3/datavis#5]
pg 315 (Random Walks) to pg 323 (Altering the Size to fill the Screen)

Submit a Pull Request from a branch with just this section's work and we can link it to this issue.

**Comment by Kraft-Bandicoot** [comment]
`from random import choice

class RandomWalk:
    # Generates random walks

    def __init__(self, num_points=5000):
        self.num_points = num_points

        # All walk start at (0, 0)
        self.x_values = [0]
        self.y_values = [0]

    def fill_walk(self):
        # keep taking steps until the walk reaches the desired length
        while len(self.x_values) < self.num_points:
            # decide which direction and how far to go
            x_direction = choice([1, -1])
            x_distance = choice([0, 1, 2, 3, 4])
            x_step = x_direction * x_distance

            y_direction = choice([1, -1])
            y_distance = choice([1, 2, 3, 4])
            y_step = y_direction * y_distance

            # reject moves that go nowhere
            if x_step == 0 and y_step == 0:
                continue

            # calculate new position
            x = self.x_values[-1] + x_step
            y = self.y_values[-1] + y_step

            self.x_values.append(x)
            self.y_values.append(y)`

**Comment by Kraft-Bandicoot** [comment]
`import matplotlib.pyplot as plt

from RandomWalk import RandomWalk

while True:
    rw = RandomWalk(50_000)
    rw.fill_walk()

    # plot the points in the walk
    plt.style.use('classic')
    fig, ax = plt.subplots(figsize=(15, 9), dpi=128)
    point_numbers = range(rw.num_points)
    ax.scatter(rw.x_values, rw.y_values, c=point_numbers, cmap=plt.cm.Purples, edgecolors='none', s=1)

    # emphasize the first and last points
    ax.scatter(0, 0, c='green', edgecolors='none', s=100)
    ax.scatter(rw.x_values[-1], rw.y_values[-1], c='red', edgecolors='none', s=100)

    # Remove the axis
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)

    plt.show()

    keep_running = input("Make another walk? (y/n): ")
    if keep_running == 'n':
        break
`

**Comment by SerenaWhite** [comment]
Both random_walk and rw_visual seem correct

**Comment by SerenaWhite** [comment]
Fixed via pull request #21
