### ISSUE TITLE
Rolling Dice with Plotly (Section 3)

### ISSUE THREAD

**Issue by SerenaWhite** [DataVis3/datavis#6]
pg 323 (Rolling Dice with Plotly-Ch 15) to pg 331 (ch 15 End

Submit a Pull Request from a branch with just this section's work and we can link it to this issue.

**Comment by Kraft-Bandicoot** [comment]
`from random import randint

class Die:
    def __init__(self, num_sides=6):
        self.num_sides = num_sides

    def roll(self):
        return randint(1, self.num_sides)`

**Comment by Kraft-Bandicoot** [comment]
`from plotly.graph_objs import Bar, Layout
from plotly import offline

from DieClass import Die

# create a D6 and a D10
die_1 = Die()
die_2 = Die(10)

results = []
for roll_num in range(50_000):
    result = die_1.roll() + die_2.roll()
    results.append(result)

# analyze the results
frequencies = []
max_result = die_1.num_sides + die_2.num_sides
for value in range(2, max_result+1):
    frequency = results.count(value)
    frequencies.append(frequency)

# visualize the results
x_values = list(range(2, max_result+1))
data = [Bar(x=x_values, y=frequencies)]

x_axis_config = {'title': 'Result', 'dtick': 1}
y_axis_config = {'title': 'Frequency of Result'}
my_layout = Layout(title='Results of rolling a D6 and a D10 50,000 times', xaxis = x_axis_config, yaxis = y_axis_config)
offline.plot({'data': data, 'layout': my_layout}, filename='d6_d10.html')

print(frequencies)`

**Comment by SerenaWhite** [comment]
The only notable things are that since the provided documents are the final ones, the HTML files from the past sections, such as d6_d6.html will not show up.

**Comment by SerenaWhite** [comment]
Fixed via pull requests #22 and #23
